### ISSUE TITLE
No Fall Damage

### ISSUE THREAD

**Issue by Zephreo** [Pwnion/DestinyMC#4] opened 2018-12-20 01:05 UTC
Fall damage is not applied at
12 Blocks
17 Blocks
20 Blocks
23 Blocks
25 Blocks
28 Blocks
30 Blocks
33 Blocks

I have only tested up to 33 blocks high

**Comment by Pwnion** [comment] 2018-12-20 01:09
Also when you just walk off a high block instead of jumping off it.

**Comment by Pwnion** [comment] 2018-12-21 11:42
The problem was that at certain heights, the player involuntarily got moved a minuscule amount on landing. This resulted in the playerMoveEvent triggering one two many times, enabling flight before fall damage was applied to the player. This has been fixed by pull request #15 .

**Comment by Pwnion** [comment] 2018-12-22 00:09
I now completely understand why this bug is occuring, after some tests. Solution should hopefully come some time today

**Comment by Pwnion** [comment] 2018-12-23 07:08
The full extent of the issue is as follows: since the playerMoveEvent can only run at a maximum of once every tick, when a player was falling both fast enough, and from a height that conveniently ran the code just before one block above the ground, but wasn't fast enough to run again before the player hit the ground, there wasn't enough time to disable flight so the player could take fall damage. The first good solution to this problem was to check two or more blocks at a time below the player instead of one, but if the platform the player was landing on was only one block in depth, they still wouldn't take fall damage if they were at a certain height and were falling at a fast enough velocity. It also increased the amount of resources the plugin was using. The final solution, as seen in pull request #17, involves recording a players fall distance and manually applying fall damage when they hit the ground, so it no longer matters whether they have flight enabled when they hit the ground.

**Closed by Pwnion** 2018-12-23 07:08 UTC
Labels: bug
